name = input("What is your name?")
print(f"Hello {name}")
print("Today we will tell a story at the beach")      
print ("")
print("")
friendsname = input("Pick one of your friends name")
things = input("Now pick 2 plural nouns")
noun = input ("Lastly, pick one more noun")
print ("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*")
print(f"{name} went to the beach with {friendsname}")
print ("First, they swam in the ocean.")
print ("Then, they saw {nouns}")
print ("Lastly, they built a sandcastle out of {noun}")
print ("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*")